const CVdataRows=[
  {
    nombres:'valeria',
    apellidos:'meneses',
    sexo:'Female',
    fechaNacimiento:'1993-02-18',
    direccion:'Av. morelos 12 totolandia',
    telefono: '2222222222',
    email:'val@mail.com',
    nombreInstituto:'UTTEC',
    tituloAdquirido:'biotecnologia',
    fechaInicioEdu:'2012-01-22',
    fechaTerminoEdu:'2015-10-22',
    cedula:'123456',
    puesto:'tec laboratorista',
    funciones:'extraccion de adn',
    empresa:'CIMMIT',
    fechaInicioExp:'2014-08-22',
    fechaTerminoExp:'2015-08-22',
    cursos:'hambiental, otro, otro',
    seminarios:'otro, otro, otro',
    diplomados:'ninguno',
    publicaciones:'nada',
    otros:'otro',
    idiomas:'ingles',
    entrevistado:1,
    note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    trabajoEquipo: 10,
    liderazgo: 9,
    conocimientoTecnico:8,
    facilidadComunicacion: 10,
    creatividad:8
  },
  {
    nombres:'oscar',
    apellidos:'aguilar',
    sexo:'Male',
    fechaNacimiento:'1990-12-22',
    direccion:'Av. morelos 12 Totolcingo',
    telefono: '5555555555',
    email:'oscar@mail.com',
    nombreInstituto:'UTTEC',
    tituloAdquirido:'administracion',
    fechaInicioEdu:'2012-01-22',
    fechaTerminoEdu:'2015-10-22',
    cedula:'123456',
    puesto:'recursos humanos',
    funciones:'reclutacion',
    empresa:'FITSA',
    fechaInicioExp:'2014-08-22',
    fechaTerminoExp:'2015-08-22',
    cursos:'admon, otro, otro',
    seminarios:'admon, otro, otro',
    diplomados:'ninguno',
    publicaciones:'nada',
    otros:'otro',
    idiomas:'ingles',
    entrevistado:1,
    note: 'Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    trabajoEquipo: 9,
    liderazgo: 9,
    conocimientoTecnico:8,
    facilidadComunicacion: 8,
    creatividad:8
  },
  {
    "nombres":"Cullin","apellidos":"Pilcher","sexo":"Male","fechaNacimiento":"1970-05-07","direccion":"07097 Badeau Circle","telefono":"797 849 7281","email":"cpilcher0@youtube.com","nombreInstituto":"Ukrainian Medical Stomatological Academy","tituloAdquirido":"Quality Control Specialist","fechaInicioEdu":"2006-02-22","fechaTerminoEdu":"2001-08-11","cedula":602,"puesto":"Accounting","funciones":"regional","empresa":"Gigaclub","fechaInicioExp":"2001-06-05","fechaTerminoExp":"2003-09-19","cursos":"varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus","seminarios":"n/a","diplomados":"Basic Industries","publicaciones":"e-enable extensible initiatives","otros":"Center","idiomas":"Catalan","entrevistado":false,"note":"imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci","trabajoEquipo":2,"liderazgo":3,"conocimientoTecnico":10,"facilidadComunicacion":5,"creatividad":7},
  {
    "nombres":"Hazlett","apellidos":"Gerling","sexo":"Male","fechaNacimiento":"1998-05-04","direccion":"185 Grover Avenue","telefono":"223 601 0799","email":"hgerling1@usa.gov","nombreInstituto":"Universidad Interamericana de Puerto Rico, San Germán","tituloAdquirido":"Community Outreach Specialist","fechaInicioEdu":"2006-02-25","fechaTerminoEdu":"2002-02-04","cedula":237,"puesto":"Services","funciones":"Visionary","empresa":"Wikivu","fechaInicioExp":"1992-06-18","fechaTerminoExp":"2000-04-15","cursos":"viverra diam vitae quam suspendisse potenti nullam porttitor lacus at","seminarios":"Public Utilities","diplomados":"Finance","publicaciones":"optimize rich channels","otros":"Lane","idiomas":"Danish","entrevistado":true,"note":"eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo","trabajoEquipo":10,"liderazgo":2,"conocimientoTecnico":9,"facilidadComunicacion":7,"creatividad":2},
  {
    "nombres":"Karoly","apellidos":"De Malchar","sexo":"Female","fechaNacimiento":"2000-01-19","direccion":"7 Main Terrace","telefono":"760 820 9241","email":"kdemalchar2@washington.edu","nombreInstituto":"Dokkyo University","tituloAdquirido":"Financial Advisor","fechaInicioEdu":"2006-03-02","fechaTerminoEdu":"2016-09-05","cedula":479,"puesto":"Engineering","funciones":"Monitored","empresa":"Gabvine","fechaInicioExp":"1995-06-09","fechaTerminoExp":"1996-09-11","cursos":"morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc","seminarios":"Consumer Durables","diplomados":"Public Utilities","publicaciones":"incentivize 24/7 models","otros":"Circle","idiomas":"Dari","entrevistado":false,"note":"fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec","trabajoEquipo":7,"liderazgo":9,"conocimientoTecnico":9,"facilidadComunicacion":2,"creatividad":5},
  {
    "nombres":"Jesselyn","apellidos":"Marcus","sexo":"Female","fechaNacimiento":"1972-05-13","direccion":"5333 Artisan Circle","telefono":"162 455 2534","email":"jmarcus3@elpais.com","nombreInstituto":"Kitami Institute of Technology","tituloAdquirido":"Registered Nurse","fechaInicioEdu":"2008-09-24","fechaTerminoEdu":"1994-02-05","cedula":310,"puesto":"Sales","funciones":"Advanced","empresa":"Browsebug","fechaInicioExp":"1993-04-02","fechaTerminoExp":"1990-08-10","cursos":"ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat","seminarios":"Technology","diplomados":"Public Utilities","publicaciones":"embrace leading-edge interfaces","otros":"Park","idiomas":"Romanian","entrevistado":false,"note":"pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet","trabajoEquipo":7,"liderazgo":6,"conocimientoTecnico":6,"facilidadComunicacion":7,"creatividad":7},
  {
    "nombres":"Levey","apellidos":"Hardwicke","sexo":"Male","fechaNacimiento":"1970-02-01","direccion":"3759 Evergreen Crossing","telefono":"495 527 0607","email":"lhardwicke4@narod.ru","nombreInstituto":"Yamanashi Medical University","tituloAdquirido":"Senior Financial Analyst","fechaInicioEdu":"2011-09-11","fechaTerminoEdu":"2013-09-05","cedula":280,"puesto":"Engineering","funciones":"client-driven","empresa":"Voonix","fechaInicioExp":"2012-05-09","fechaTerminoExp":"1994-09-13","cursos":"amet erat nulla tempus vivamus in felis","seminarios":"Consumer Durables","diplomados":"n/a","publicaciones":"maximize bricks-and-clicks infrastructures","otros":"Crossing","idiomas":"Croatian","entrevistado":false,"note":"nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget","trabajoEquipo":7,"liderazgo":4,"conocimientoTecnico":4,"facilidadComunicacion":8,"creatividad":7},
  {
    "nombres":"Clevie","apellidos":"Blesdill","sexo":"Male","fechaNacimiento":"1978-11-13","direccion":"423 Hollow Ridge Trail","telefono":"539 874 6858","email":"cblesdill5@wikia.com","nombreInstituto":"Heilongjiang August 1st Reclamation University","tituloAdquirido":"Computer Systems Analyst IV","fechaInicioEdu":"1994-02-18","fechaTerminoEdu":"1999-05-19","cedula":786,"puesto":"Marketing","funciones":"bandwidth-monitored","empresa":"Yacero","fechaInicioExp":"1990-11-17","fechaTerminoExp":"1993-12-13","cursos":"nec nisi volutpat eleifend donec ut dolor morbi vel","seminarios":"Consumer Durables","diplomados":"Consumer Services","publicaciones":"grow open-source channels","otros":"Alley","idiomas":"Zulu","entrevistado":true,"note":"lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec","trabajoEquipo":10,"liderazgo":3,"conocimientoTecnico":7,"facilidadComunicacion":3,"creatividad":8},
  {
    "nombres":"Lois","apellidos":"Waterstone","sexo":"Female","fechaNacimiento":"1990-01-30","direccion":"36 Huxley Drive","telefono":"561 536 7052","email":"lwaterstone6@opensource.org","nombreInstituto":"Wesleyan College","tituloAdquirido":"Technical Writer","fechaInicioEdu":"2007-02-18","fechaTerminoEdu":"2000-03-27","cedula":200,"puesto":"Business Development","funciones":"function","empresa":"Yamia","fechaInicioExp":"1990-07-27","fechaTerminoExp":"2000-12-27","cursos":"sodales scelerisque mauris sit amet eros suspendisse accumsan","seminarios":"Consumer Services","diplomados":"Capital Goods","publicaciones":"aggregate leading-edge ROI","otros":"Lane","idiomas":"Spanish","entrevistado":true,"note":"eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat","trabajoEquipo":5,"liderazgo":2,"conocimientoTecnico":5,"facilidadComunicacion":1,"creatividad":9},
  {
    "nombres":"Lindy","apellidos":"Laste","sexo":"Female","fechaNacimiento":"1994-06-06","direccion":"735 Graceland Terrace","telefono":"225 490 3783","email":"llaste7@jigsy.com","nombreInstituto":"Hemchandracharay North Gujarat University","tituloAdquirido":"Assistant Professor","fechaInicioEdu":"1998-10-29","fechaTerminoEdu":"1999-03-30","cedula":787,"puesto":"Services","funciones":"Innovative","empresa":"Podcat","fechaInicioExp":"2014-08-19","fechaTerminoExp":"1996-05-11","cursos":"mauris non ligula pellentesque ultrices phasellus id sapien in","seminarios":"Consumer Non-Durables","diplomados":"n/a","publicaciones":"extend B2C web services","otros":"Way","idiomas":"Aymara","entrevistado":true,"note":"quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede","trabajoEquipo":5,"liderazgo":9,"conocimientoTecnico":5,"facilidadComunicacion":8,"creatividad":6},
  {
    "nombres":"Neddy","apellidos":"Bantham","sexo":"Male","fechaNacimiento":"1994-01-07","direccion":"8 Marquette Center","telefono":"539 204 4573","email":"nbantham8@biglobe.ne.jp","nombreInstituto":"State University of New York College at Potsdam","tituloAdquirido":"Software Test Engineer IV","fechaInicioEdu":"2009-02-03","fechaTerminoEdu":"2000-04-07","cedula":496,"puesto":"Research and Development","funciones":"homogeneous","empresa":"Cogidoo","fechaInicioExp":"1995-05-21","fechaTerminoExp":"2013-12-25","cursos":"sit amet nulla quisque arcu libero rutrum ac","seminarios":"Finance","diplomados":"Health Care","publicaciones":"streamline plug-and-play web-readiness","otros":"Center","idiomas":"Hindi","entrevistado":true,"note":"nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis","trabajoEquipo":4,"liderazgo":9,"conocimientoTecnico":5,"facilidadComunicacion":9,"creatividad":1},
  {
    "nombres":"Matthaeus","apellidos":"McGirl","sexo":"Male","fechaNacimiento":"1971-02-20","direccion":"219 Homewood Way","telefono":"834 767 1392","email":"mmcgirl9@intel.com","nombreInstituto":"Mehrabyan Medical Institute and Medical College","tituloAdquirido":"Account Coordinator","fechaInicioEdu":"2007-06-21","fechaTerminoEdu":"2016-10-05","cedula":140,"puesto":"Support","funciones":"asynchronous","empresa":"Dabfeed","fechaInicioExp":"2001-10-04","fechaTerminoExp":"2015-11-16","cursos":"ligula vehicula consequat morbi a ipsum integer a nibh","seminarios":"Consumer Non-Durables","diplomados":"n/a","publicaciones":"reinvent open-source technologies","otros":"Alley","idiomas":"Czech","entrevistado":true,"note":"eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum","trabajoEquipo":3,"liderazgo":1,"conocimientoTecnico":6,"facilidadComunicacion":10,"creatividad":7},
  {
    "nombres":"Brooke","apellidos":"Partner","sexo":"Female","fechaNacimiento":"1987-03-24","direccion":"48824 Sullivan Center","telefono":"758 396 0399","email":"bpartnera@exblog.jp","nombreInstituto":"Gomel State Medical University","tituloAdquirido":"Clinical Specialist","fechaInicioEdu":"2005-11-12","fechaTerminoEdu":"2017-07-31","cedula":488,"puesto":"Training","funciones":"Open-source","empresa":"Zoombox","fechaInicioExp":"2013-10-10","fechaTerminoExp":"2016-01-10","cursos":"eu tincidunt in leo maecenas pulvinar","seminarios":"Capital Goods","diplomados":"Miscellaneous","publicaciones":"evolve best-of-breed synergies","otros":"Circle","idiomas":"Catalan","entrevistado":false,"note":"blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum","trabajoEquipo":4,"liderazgo":10,"conocimientoTecnico":4,"facilidadComunicacion":6,"creatividad":9},
  {
    "nombres":"Ginnie","apellidos":"Rodgier","sexo":"Female","fechaNacimiento":"1983-11-15","direccion":"3629 Nobel Court","telefono":"330 182 4884","email":"grodgierb@instagram.com","nombreInstituto":"Universidad Tecnológica de El Salvador","tituloAdquirido":"Senior Financial Analyst","fechaInicioEdu":"2014-07-12","fechaTerminoEdu":"1991-11-09","cedula":724,"puesto":"Training","funciones":"Balanced","empresa":"Wikido","fechaInicioExp":"1997-01-11","fechaTerminoExp":"2017-09-30","cursos":"convallis tortor risus dapibus augue vel","seminarios":"Health Care","diplomados":"Energy","publicaciones":"seize strategic schemas","otros":"Parkway","idiomas":"Sotho","entrevistado":true,"note":"nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus","trabajoEquipo":10,"liderazgo":3,"conocimientoTecnico":7,"facilidadComunicacion":4,"creatividad":1},
  {
    "nombres":"Quintus","apellidos":"Orans","sexo":"Male","fechaNacimiento":"1994-01-03","direccion":"3886 Dwight Avenue","telefono":"670 414 1366","email":"qoransc@reuters.com","nombreInstituto":"Shaanxi Normal University","tituloAdquirido":"Pharmacist","fechaInicioEdu":"1993-01-10","fechaTerminoEdu":"1994-12-20","cedula":820,"puesto":"Legal","funciones":"analyzing","empresa":"Twinder","fechaInicioExp":"2010-02-25","fechaTerminoExp":"1990-12-17","cursos":"vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","seminarios":"Public Utilities","diplomados":"Public Utilities","publicaciones":"streamline cross-platform web services","otros":"Crossing","idiomas":"Kazakh","entrevistado":false,"note":"massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget","trabajoEquipo":6,"liderazgo":10,"conocimientoTecnico":4,"facilidadComunicacion":2,"creatividad":1},
  {
    "nombres":"Lianna","apellidos":"Martynikhin","sexo":"Female","fechaNacimiento":"1971-06-30","direccion":"85096 Division Street","telefono":"827 531 1344","email":"lmartynikhind@dropbox.com","nombreInstituto":"Universidade Federal Rural do Rio de Janeiro","tituloAdquirido":"Nuclear Power Engineer","fechaInicioEdu":"1995-09-07","fechaTerminoEdu":"2006-04-06","cedula":935,"puesto":"Human Resources","funciones":"zero tolerance","empresa":"Gevee","fechaInicioExp":"2013-04-22","fechaTerminoExp":"2014-11-24","cursos":"ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel","seminarios":"n/a","diplomados":"Technology","publicaciones":"visualize integrated content","otros":"Drive","idiomas":"Yiddish","entrevistado":true,"note":"nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa","trabajoEquipo":6,"liderazgo":5,"conocimientoTecnico":9,"facilidadComunicacion":7,"creatividad":5},
  {
    "nombres":"Monroe","apellidos":"Spurnier","sexo":"Male","fechaNacimiento":"1997-04-21","direccion":"98 Pond Terrace","telefono":"413 657 0000","email":"mspurniere@fc2.com","nombreInstituto":"IDRAC (Institut de recherche en action commerciale)","tituloAdquirido":"Dental Hygienist","fechaInicioEdu":"1998-02-20","fechaTerminoEdu":"1999-04-18","cedula":444,"puesto":"Legal","funciones":"Phased","empresa":"Gabspot","fechaInicioExp":"1992-06-08","fechaTerminoExp":"2001-05-20","cursos":"tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum","seminarios":"Finance","diplomados":"Public Utilities","publicaciones":"transform intuitive networks","otros":"Court","idiomas":"Papiamento","entrevistado":true,"note":"mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium","trabajoEquipo":10,"liderazgo":9,"conocimientoTecnico":1,"facilidadComunicacion":10,"creatividad":1},
  {
    "nombres":"Farley","apellidos":"Antonioni","sexo":"Male","fechaNacimiento":"1975-08-26","direccion":"0548 Armistice Place","telefono":"493 309 3216","email":"fantonionif@skype.com","nombreInstituto":"Uganda Martyr's University","tituloAdquirido":"Financial Advisor","fechaInicioEdu":"1995-11-25","fechaTerminoEdu":"2017-04-25","cedula":68,"puesto":"Research and Development","funciones":"Business-focused","empresa":"Tambee","fechaInicioExp":"2003-10-09","fechaTerminoExp":"2011-04-03","cursos":"ut dolor morbi vel lectus in","seminarios":"Finance","diplomados":"Miscellaneous","publicaciones":"benchmark bleeding-edge ROI","otros":"Point","idiomas":"New Zealand Sign Language","entrevistado":true,"note":"mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit","trabajoEquipo":1,"liderazgo":2,"conocimientoTecnico":3,"facilidadComunicacion":7,"creatividad":7},
  {
    "nombres":"Stillmann","apellidos":"Rodwell","sexo":"Male","fechaNacimiento":"1988-04-05","direccion":"12 Grover Park","telefono":"548 148 6113","email":"srodwellg@usnews.com","nombreInstituto":"California State University, Los Angeles","tituloAdquirido":"Financial Advisor","fechaInicioEdu":"1999-04-05","fechaTerminoEdu":"2009-01-15","cedula":315,"puesto":"Sales","funciones":"task-force","empresa":"Agivu","fechaInicioExp":"2005-12-26","fechaTerminoExp":"1990-07-31","cursos":"elit proin risus praesent lectus vestibulum","seminarios":"Transportation","diplomados":"n/a","publicaciones":"deliver intuitive methodologies","otros":"Lane","idiomas":"Polish","entrevistado":false,"note":"vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing","trabajoEquipo":9,"liderazgo":4,"conocimientoTecnico":3,"facilidadComunicacion":9,"creatividad":1},
  {
    "nombres":"Alberto","apellidos":"Summerrell","sexo":"Male","fechaNacimiento":"1980-06-06","direccion":"8 Raven Street","telefono":"852 935 7713","email":"asummerrellh@prweb.com","nombreInstituto":"Technical University of Crete","tituloAdquirido":"Budget/Accounting Analyst III","fechaInicioEdu":"2016-03-24","fechaTerminoEdu":"2014-11-30","cedula":399,"puesto":"Accounting","funciones":"context-sensitive","empresa":"Voomm","fechaInicioExp":"2017-01-08","fechaTerminoExp":"2013-11-17","cursos":"amet eros suspendisse accumsan tortor quis turpis sed ante","seminarios":"Consumer Services","diplomados":"Miscellaneous","publicaciones":"scale dot-com web services","otros":"Trail","idiomas":"Marathi","entrevistado":false,"note":"nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam","trabajoEquipo":9,"liderazgo":9,"conocimientoTecnico":8,"facilidadComunicacion":5,"creatividad":8},
  {
    "nombres":"Giordano","apellidos":"Salomon","sexo":"Male","fechaNacimiento":"1982-11-09","direccion":"957 Del Mar Lane","telefono":"545 240 5001","email":"gsalomoni@marriott.com","nombreInstituto":"Newman University","tituloAdquirido":"VP Marketing","fechaInicioEdu":"1996-09-06","fechaTerminoEdu":"2008-02-09","cedula":860,"puesto":"Services","funciones":"Cross-group","empresa":"Mudo","fechaInicioExp":"2000-10-07","fechaTerminoExp":"2006-02-16","cursos":"nisl aenean lectus pellentesque eget nunc donec quis orci eget","seminarios":"Health Care","diplomados":"Technology","publicaciones":"strategize killer schemas","otros":"Drive","idiomas":"Persian","entrevistado":true,"note":"lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor","trabajoEquipo":10,"liderazgo":7,"conocimientoTecnico":1,"facilidadComunicacion":3,"creatividad":3},
  {
    "nombres":"Ellis","apellidos":"Sakins","sexo":"Male","fechaNacimiento":"1971-11-01","direccion":"13231 Ronald Regan Drive","telefono":"143 460 4776","email":"esakinsj@odnoklassniki.ru","nombreInstituto":"Chubu Gakuin University & Chubu Women's College","tituloAdquirido":"Nuclear Power Engineer","fechaInicioEdu":"2000-11-17","fechaTerminoEdu":"2011-09-01","cedula":267,"puesto":"Human Resources","funciones":"project","empresa":"Fiveclub","fechaInicioExp":"2007-01-18","fechaTerminoExp":"1999-11-17","cursos":"feugiat non pretium quis lectus suspendisse potenti in","seminarios":"Technology","diplomados":"Consumer Services","publicaciones":"architect bleeding-edge experiences","otros":"Crossing","idiomas":"Haitian Creole","entrevistado":false,"note":"quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst","trabajoEquipo":9,"liderazgo":6,"conocimientoTecnico":9,"facilidadComunicacion":8,"creatividad":10},
  {
    "nombres":"Kellina","apellidos":"McGaw","sexo":"Female","fechaNacimiento":"1978-04-19","direccion":"24182 Dahle Parkway","telefono":"334 614 7357","email":"kmcgawk@stumbleupon.com","nombreInstituto":"Hesser College","tituloAdquirido":"Health Coach III","fechaInicioEdu":"2012-09-10","fechaTerminoEdu":"2009-04-19","cedula":923,"puesto":"Sales","funciones":"Virtual","empresa":"Divape","fechaInicioExp":"1998-10-23","fechaTerminoExp":"2001-12-02","cursos":"felis sed lacus morbi sem mauris","seminarios":"Basic Industries","diplomados":"Consumer Non-Durables","publicaciones":"innovate bleeding-edge niches","otros":"Street","idiomas":"Hebrew","entrevistado":false,"note":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec","trabajoEquipo":1,"liderazgo":1,"conocimientoTecnico":9,"facilidadComunicacion":2,"creatividad":2},
  {
    "nombres":"Donny","apellidos":"Sawney","sexo":"Female","fechaNacimiento":"1987-06-13","direccion":"39 Lien Street","telefono":"566 441 2966","email":"dsawneyl@nytimes.com","nombreInstituto":"Keck Graduate Institute of Applied Life Sciences","tituloAdquirido":"Accounting Assistant I","fechaInicioEdu":"2013-01-14","fechaTerminoEdu":"1995-11-05","cedula":253,"puesto":"Research and Development","funciones":"context-sensitive","empresa":"Gabvine","fechaInicioExp":"1999-05-20","fechaTerminoExp":"2008-05-05","cursos":"nullam porttitor lacus at turpis donec posuere metus vitae ipsum","seminarios":"Consumer Non-Durables","diplomados":"Technology","publicaciones":"drive scalable infomediaries","otros":"Trail","idiomas":"West Frisian","entrevistado":true,"note":"velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio","trabajoEquipo":8,"liderazgo":9,"conocimientoTecnico":8,"facilidadComunicacion":1,"creatividad":8},
  {
    "nombres":"Rubin","apellidos":"Hovel","sexo":"Male","fechaNacimiento":"1970-06-15","direccion":"824 Johnson Way","telefono":"510 714 9285","email":"rhovelm@skype.com","nombreInstituto":"Lorestan University","tituloAdquirido":"VP Accounting","fechaInicioEdu":"2001-08-07","fechaTerminoEdu":"1992-04-03","cedula":475,"puesto":"Accounting","funciones":"local","empresa":"Skivee","fechaInicioExp":"1996-09-04","fechaTerminoExp":"1999-06-16","cursos":"magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","seminarios":"Consumer Services","diplomados":"Finance","publicaciones":"reintermediate global niches","otros":"Way","idiomas":"Malagasy","entrevistado":true,"note":"leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris","trabajoEquipo":5,"liderazgo":8,"conocimientoTecnico":1,"facilidadComunicacion":5,"creatividad":7},
  {
    "nombres":"Philip","apellidos":"Busfield","sexo":"Male","fechaNacimiento":"1983-03-05","direccion":"25608 Evergreen Crossing","telefono":"273 617 0322","email":"pbusfieldn@usda.gov","nombreInstituto":"Syktyvkar State University","tituloAdquirido":"Product Engineer","fechaInicioEdu":"1999-10-30","fechaTerminoEdu":"1991-02-11","cedula":942,"puesto":"Human Resources","funciones":"monitoring","empresa":"Tagchat","fechaInicioExp":"2008-08-13","fechaTerminoExp":"2000-12-04","cursos":"nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at","seminarios":"n/a","diplomados":"Capital Goods","publicaciones":"innovate back-end e-markets","otros":"Way","idiomas":"Belarusian","entrevistado":true,"note":"amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur","trabajoEquipo":3,"liderazgo":5,"conocimientoTecnico":4,"facilidadComunicacion":2,"creatividad":4},
  {
    "nombres":"Neall","apellidos":"Doram","sexo":"Male","fechaNacimiento":"1987-02-19","direccion":"669 Steensland Circle","telefono":"833 587 8397","email":"ndoramo@oaic.gov.au","nombreInstituto":"Deakin University","tituloAdquirido":"Computer Systems Analyst III","fechaInicioEdu":"1996-08-07","fechaTerminoEdu":"1993-09-18","cedula":441,"puesto":"Services","funciones":"optimizing","empresa":"Thoughtworks","fechaInicioExp":"2012-12-17","fechaTerminoExp":"1993-01-03","cursos":"quis tortor id nulla ultrices aliquet","seminarios":"n/a","diplomados":"n/a","publicaciones":"harness clicks-and-mortar web services","otros":"Street","idiomas":"Spanish","entrevistado":true,"note":"tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum","trabajoEquipo":9,"liderazgo":4,"conocimientoTecnico":9,"facilidadComunicacion":6,"creatividad":9},
  {
    "nombres":"Ailene","apellidos":"Vigours","sexo":"Female","fechaNacimiento":"1981-12-02","direccion":"36 Farmco Hill","telefono":"348 194 1801","email":"avigoursp@tumblr.com","nombreInstituto":"Eastern New Mexico University","tituloAdquirido":"Speech Pathologist","fechaInicioEdu":"1994-07-22","fechaTerminoEdu":"2008-06-25","cedula":924,"puesto":"Accounting","funciones":"zero administration","empresa":"Izio","fechaInicioExp":"1995-07-12","fechaTerminoExp":"2003-09-09","cursos":"aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam","seminarios":"n/a","diplomados":"Technology","publicaciones":"exploit web-enabled eyeballs","otros":"Crossing","idiomas":"Pashto","entrevistado":false,"note":"in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci","trabajoEquipo":10,"liderazgo":5,"conocimientoTecnico":3,"facilidadComunicacion":5,"creatividad":8},
  {
    "nombres":"Lanita","apellidos":"Postins","sexo":"Female","fechaNacimiento":"1995-12-21","direccion":"12814 Emmet Trail","telefono":"491 831 8419","email":"lpostinsq@boston.com","nombreInstituto":"Murni Nursing College","tituloAdquirido":"Research Associate","fechaInicioEdu":"2007-01-21","fechaTerminoEdu":"1996-02-18","cedula":559,"puesto":"Services","funciones":"explicit","empresa":"Topicshots","fechaInicioExp":"1995-08-03","fechaTerminoExp":"1992-03-03","cursos":"sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at","seminarios":"Technology","diplomados":"n/a","publicaciones":"transform revolutionary networks","otros":"Parkway","idiomas":"Guaraní","entrevistado":true,"note":"at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis","trabajoEquipo":4,"liderazgo":2,"conocimientoTecnico":5,"facilidadComunicacion":2,"creatividad":7},
  {
    "nombres":"Zebulon","apellidos":"Tregien","sexo":"Male","fechaNacimiento":"1971-04-26","direccion":"57 Maywood Road","telefono":"123 434 0370","email":"ztregienr@oracle.com","nombreInstituto":"Medical Academy Ludwik Rydygier in Bydgoszcz","tituloAdquirido":"Geologist IV","fechaInicioEdu":"2008-02-23","fechaTerminoEdu":"2017-01-19","cedula":736,"puesto":"Product Management","funciones":"capacity","empresa":"Trudeo","fechaInicioExp":"2005-10-15","fechaTerminoExp":"2011-11-02","cursos":"ipsum primis in faucibus orci luctus et ultrices posuere cubilia","seminarios":"n/a","diplomados":"Finance","publicaciones":"e-enable plug-and-play models","otros":"Park","idiomas":"Kurdish","entrevistado":false,"note":"proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat","trabajoEquipo":3,"liderazgo":6,"conocimientoTecnico":7,"facilidadComunicacion":8,"creatividad":3},
  {
    "nombres":"Maynard","apellidos":"Gatchell","sexo":"Male","fechaNacimiento":"1994-10-10","direccion":"26624 Roxbury Park","telefono":"872 597 5761","email":"mgatchells@rediff.com","nombreInstituto":"Indian University","tituloAdquirido":"VP Sales","fechaInicioEdu":"1995-01-02","fechaTerminoEdu":"2003-02-09","cedula":922,"puesto":"Engineering","funciones":"success","empresa":"Avamba","fechaInicioExp":"1996-05-10","fechaTerminoExp":"2012-07-06","cursos":"sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus","seminarios":"n/a","diplomados":"Technology","publicaciones":"revolutionize revolutionary architectures","otros":"Place","idiomas":"Gujarati","entrevistado":false,"note":"nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede","trabajoEquipo":7,"liderazgo":1,"conocimientoTecnico":1,"facilidadComunicacion":2,"creatividad":7},
  {
    "nombres":"Trescha","apellidos":"Zimmermeister","sexo":"Female","fechaNacimiento":"1978-04-29","direccion":"67 Oak Junction","telefono":"557 307 4806","email":"tzimmermeistert@i2i.jp","nombreInstituto":"University of Phoenix","tituloAdquirido":"Assistant Media Planner","fechaInicioEdu":"1995-02-20","fechaTerminoEdu":"2002-12-27","cedula":48,"puesto":"Training","funciones":"coherent","empresa":"Meevee","fechaInicioExp":"2013-07-26","fechaTerminoExp":"1996-02-07","cursos":"in magna bibendum imperdiet nullam orci pede venenatis non","seminarios":"Finance","diplomados":"n/a","publicaciones":"generate world-class web services","otros":"Terrace","idiomas":"Hiri Motu","entrevistado":true,"note":"congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales","trabajoEquipo":3,"liderazgo":2,"conocimientoTecnico":4,"facilidadComunicacion":10,"creatividad":4},
  {
    "nombres":"Nicola","apellidos":"Broddle","sexo":"Male","fechaNacimiento":"1983-01-17","direccion":"61628 Summerview Park","telefono":"250 617 2753","email":"nbroddleu@hatena.ne.jp","nombreInstituto":"Allameh Tabatabaie University","tituloAdquirido":"Analyst Programmer","fechaInicioEdu":"1992-07-08","fechaTerminoEdu":"2001-12-30","cedula":169,"puesto":"Sales","funciones":"Operative","empresa":"Skivee","fechaInicioExp":"2004-11-09","fechaTerminoExp":"2009-09-03","cursos":"nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti","seminarios":"n/a","diplomados":"Finance","publicaciones":"repurpose global platforms","otros":"Pass","idiomas":"Dhivehi","entrevistado":false,"note":"at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus","trabajoEquipo":3,"liderazgo":5,"conocimientoTecnico":3,"facilidadComunicacion":10,"creatividad":6},
  {
    "nombres":"Elisabet","apellidos":"Detloff","sexo":"Female","fechaNacimiento":"1984-08-04","direccion":"3397 Lake View Point","telefono":"597 675 9180","email":"edetloffv@rediff.com","nombreInstituto":"University of Wisconsin - Superior","tituloAdquirido":"Occupational Therapist","fechaInicioEdu":"2016-02-01","fechaTerminoEdu":"2015-08-26","cedula":120,"puesto":"Business Development","funciones":"Programmable","empresa":"Twitterwire","fechaInicioExp":"1996-02-13","fechaTerminoExp":"1999-05-28","cursos":"accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec","seminarios":"Finance","diplomados":"Health Care","publicaciones":"generate 24/365 relationships","otros":"Alley","idiomas":"Kazakh","entrevistado":false,"note":"in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu","trabajoEquipo":3,"liderazgo":4,"conocimientoTecnico":4,"facilidadComunicacion":9,"creatividad":3},
  {
    "nombres":"Klarrisa","apellidos":"Bent","sexo":"Female","fechaNacimiento":"1999-04-30","direccion":"3 Bluejay Alley","telefono":"744 461 0698","email":"kbentw@wix.com","nombreInstituto":"Iranian Academy of Persian Language and Literature","tituloAdquirido":"Environmental Specialist","fechaInicioEdu":"1998-11-28","fechaTerminoEdu":"1996-09-27","cedula":316,"puesto":"Services","funciones":"projection","empresa":"Photofeed","fechaInicioExp":"2009-04-18","fechaTerminoExp":"1992-05-17","cursos":"at ipsum ac tellus semper interdum mauris ullamcorper purus","seminarios":"Consumer Services","diplomados":"Technology","publicaciones":"aggregate cutting-edge networks","otros":"Park","idiomas":"Greek","entrevistado":true,"note":"nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem","trabajoEquipo":2,"liderazgo":2,"conocimientoTecnico":2,"facilidadComunicacion":2,"creatividad":6},
  {
    "nombres":"Raddy","apellidos":"Josse","sexo":"Male","fechaNacimiento":"1993-06-23","direccion":"9690 Mariners Cove Park","telefono":"454 992 5184","email":"rjossex@ucsd.edu","nombreInstituto":"Sree Rama Krishna Degree College","tituloAdquirido":"Director of Sales","fechaInicioEdu":"2002-06-26","fechaTerminoEdu":"2006-05-18","cedula":50,"puesto":"Business Development","funciones":"Reverse-engineered","empresa":"Geba","fechaInicioExp":"2001-05-01","fechaTerminoExp":"2010-05-02","cursos":"eget massa tempor convallis nulla neque libero convallis","seminarios":"n/a","diplomados":"Health Care","publicaciones":"strategize dynamic relationships","otros":"Hill","idiomas":"Swati","entrevistado":false,"note":"in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros","trabajoEquipo":2,"liderazgo":4,"conocimientoTecnico":4,"facilidadComunicacion":5,"creatividad":2},
  {
    "nombres":"Findley","apellidos":"Bullan","sexo":"Male","fechaNacimiento":"1981-09-15","direccion":"144 Ridgeway Avenue","telefono":"146 466 6564","email":"fbullany@joomla.org","nombreInstituto":"Cheljabinsk State University","tituloAdquirido":"Nurse Practicioner","fechaInicioEdu":"1991-07-19","fechaTerminoEdu":"1992-08-15","cedula":99,"puesto":"Sales","funciones":"Cloned","empresa":"Innojam","fechaInicioExp":"2000-09-13","fechaTerminoExp":"1993-02-26","cursos":"commodo vulputate justo in blandit","seminarios":"Consumer Non-Durables","diplomados":"Finance","publicaciones":"enable revolutionary interfaces","otros":"Hill","idiomas":"Finnish","entrevistado":false,"note":"amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi","trabajoEquipo":7,"liderazgo":9,"conocimientoTecnico":5,"facilidadComunicacion":2,"creatividad":4},
  {
    "nombres":"Auroora","apellidos":"Quixley","sexo":"Female","fechaNacimiento":"1998-09-24","direccion":"995 Mayfield Parkway","telefono":"393 326 4671","email":"aquixleyz@ameblo.jp","nombreInstituto":"University of Turin","tituloAdquirido":"Product Engineer","fechaInicioEdu":"2011-01-02","fechaTerminoEdu":"2009-02-04","cedula":621,"puesto":"Services","funciones":"focus group","empresa":"Trudeo","fechaInicioExp":"2005-11-05","fechaTerminoExp":"2008-08-02","cursos":"morbi ut odio cras mi pede malesuada in imperdiet","seminarios":"Finance","diplomados":"Consumer Services","publicaciones":"evolve sticky technologies","otros":"Street","idiomas":"Croatian","entrevistado":false,"note":"amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut","trabajoEquipo":5,"liderazgo":5,"conocimientoTecnico":3,"facilidadComunicacion":1,"creatividad":5},
  {
    "nombres":"Paquito","apellidos":"McKerton","sexo":"Male","fechaNacimiento":"1973-12-10","direccion":"8 Union Street","telefono":"112 247 4093","email":"pmckerton10@patch.com","nombreInstituto":"Hochschule Mittweida (FH)","tituloAdquirido":"Statistician II","fechaInicioEdu":"2000-12-11","fechaTerminoEdu":"2014-01-23","cedula":67,"puesto":"Engineering","funciones":"Configurable","empresa":"Skinix","fechaInicioExp":"2007-03-02","fechaTerminoExp":"2003-05-21","cursos":"amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam","seminarios":"Technology","diplomados":"Technology","publicaciones":"monetize 24/7 paradigms","otros":"Pass","idiomas":"Romanian","entrevistado":true,"note":"consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis","trabajoEquipo":3,"liderazgo":3,"conocimientoTecnico":3,"facilidadComunicacion":9,"creatividad":6},
  {
    "nombres":"Jaquith","apellidos":"Sprosson","sexo":"Female","fechaNacimiento":"1985-02-17","direccion":"332 Barnett Plaza","telefono":"639 529 5080","email":"jsprosson11@imageshack.us","nombreInstituto":"Université Abdou Moumouni de Niamey","tituloAdquirido":"Programmer Analyst IV","fechaInicioEdu":"1994-09-13","fechaTerminoEdu":"2012-12-01","cedula":470,"puesto":"Product Management","funciones":"project","empresa":"Realcube","fechaInicioExp":"2001-12-25","fechaTerminoExp":"2017-09-01","cursos":"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus","seminarios":"Technology","diplomados":"Health Care","publicaciones":"generate B2B systems","otros":"Circle","idiomas":"Burmese","entrevistado":false,"note":"donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing","trabajoEquipo":6,"liderazgo":4,"conocimientoTecnico":10,"facilidadComunicacion":5,"creatividad":1},
  {
    "nombres":"Rosanna","apellidos":"Jaggi","sexo":"Female","fechaNacimiento":"1993-12-14","direccion":"379 Graceland Court","telefono":"662 324 6885","email":"rjaggi12@amazon.co.jp","nombreInstituto":"Universidade do Sul de Santa Catarina","tituloAdquirido":"Professor","fechaInicioEdu":"1998-02-17","fechaTerminoEdu":"2002-08-22","cedula":81,"puesto":"Research and Development","funciones":"disintermediate","empresa":"Centimia","fechaInicioExp":"2006-08-11","fechaTerminoExp":"2014-12-11","cursos":"ipsum primis in faucibus orci luctus et ultrices posuere","seminarios":"Consumer Services","diplomados":"Finance","publicaciones":"optimize end-to-end models","otros":"Center","idiomas":"Papiamento","entrevistado":false,"note":"porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna","trabajoEquipo":10,"liderazgo":6,"conocimientoTecnico":3,"facilidadComunicacion":3,"creatividad":10},
  {
    "nombres":"Loni","apellidos":"Rookes","sexo":"Female","fechaNacimiento":"1999-11-26","direccion":"316 Center Plaza","telefono":"904 550 4156","email":"lrookes13@smugmug.com","nombreInstituto":"University of Italian Studies for Foreigners of Perugia","tituloAdquirido":"Account Coordinator","fechaInicioEdu":"2008-07-31","fechaTerminoEdu":"2008-02-20","cedula":495,"puesto":"Training","funciones":"human-resource","empresa":"Voolith","fechaInicioExp":"2004-09-07","fechaTerminoExp":"2012-02-05","cursos":"nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum","seminarios":"Consumer Services","diplomados":"Technology","publicaciones":"target scalable metrics","otros":"Circle","idiomas":"Luxembourgish","entrevistado":false,"note":"auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque","trabajoEquipo":1,"liderazgo":4,"conocimientoTecnico":10,"facilidadComunicacion":3,"creatividad":9},
  {
    "nombres":"Bobina","apellidos":"McJury","sexo":"Female","fechaNacimiento":"1974-11-27","direccion":"501 Basil Center","telefono":"403 926 3919","email":"bmcjury14@live.com","nombreInstituto":"Mersin University","tituloAdquirido":"Operator","fechaInicioEdu":"2010-07-25","fechaTerminoEdu":"2001-03-17","cedula":347,"puesto":"Training","funciones":"Triple-buffered","empresa":"JumpXS","fechaInicioExp":"2013-05-09","fechaTerminoExp":"2003-03-19","cursos":"curae nulla dapibus dolor vel est donec odio","seminarios":"Energy","diplomados":"Consumer Services","publicaciones":"engineer 24/365 supply-chains","otros":"Park","idiomas":"Bosnian","entrevistado":false,"note":"sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet","trabajoEquipo":7,"liderazgo":9,"conocimientoTecnico":6,"facilidadComunicacion":3,"creatividad":10},
  {
    "nombres":"Sibilla","apellidos":"Leng","sexo":"Female","fechaNacimiento":"1986-06-26","direccion":"66364 Towne Alley","telefono":"368 552 7232","email":"sleng15@oracle.com","nombreInstituto":"Technical University of Cracow","tituloAdquirido":"Structural Engineer","fechaInicioEdu":"1992-08-14","fechaTerminoEdu":"2010-11-29","cedula":635,"puesto":"Business Development","funciones":"impactful","empresa":"Skimia","fechaInicioExp":"2000-10-24","fechaTerminoExp":"2008-08-04","cursos":"hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci","seminarios":"Finance","diplomados":"Technology","publicaciones":"harness frictionless deliverables","otros":"Pass","idiomas":"Bulgarian","entrevistado":true,"note":"quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna","trabajoEquipo":10,"liderazgo":7,"conocimientoTecnico":3,"facilidadComunicacion":7,"creatividad":3},
  {
    "nombres":"Brianne","apellidos":"Cruddace","sexo":"Female","fechaNacimiento":"1970-03-26","direccion":"896 Kingsford Parkway","telefono":"995 696 0624","email":"bcruddace16@rediff.com","nombreInstituto":"Oglethorpe University","tituloAdquirido":"Account Coordinator","fechaInicioEdu":"1995-09-26","fechaTerminoEdu":"1991-02-17","cedula":872,"puesto":"Support","funciones":"discrete","empresa":"Twitterbridge","fechaInicioExp":"1992-07-31","fechaTerminoExp":"2014-07-09","cursos":"proin at turpis a pede posuere nonummy integer non velit donec diam neque","seminarios":"Finance","diplomados":"Capital Goods","publicaciones":"deploy mission-critical convergence","otros":"Alley","idiomas":"Tswana","entrevistado":true,"note":"id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu","trabajoEquipo":6,"liderazgo":7,"conocimientoTecnico":2,"facilidadComunicacion":8,"creatividad":5},
  {
    "nombres":"Eben","apellidos":"Carlisso","sexo":"Male","fechaNacimiento":"1989-07-24","direccion":"24 Dwight Court","telefono":"155 323 1849","email":"ecarlisso17@mail.ru","nombreInstituto":"Shenyang Pharmaceutical University","tituloAdquirido":"VP Marketing","fechaInicioEdu":"2005-12-25","fechaTerminoEdu":"1998-05-05","cedula":588,"puesto":"Legal","funciones":"zero administration","empresa":"Reallinks","fechaInicioExp":"1997-03-11","fechaTerminoExp":"2014-11-01","cursos":"vestibulum ante ipsum primis in faucibus orci luctus","seminarios":"n/a","diplomados":"n/a","publicaciones":"generate innovative supply-chains","otros":"Circle","idiomas":"Dhivehi","entrevistado":true,"note":"accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo","trabajoEquipo":3,"liderazgo":3,"conocimientoTecnico":5,"facilidadComunicacion":10,"creatividad":8},
  {
    "nombres":"Francesco","apellidos":"Sutehall","sexo":"Male","fechaNacimiento":"1978-10-30","direccion":"18897 Eliot Lane","telefono":"273 647 6708","email":"fsutehall18@craigslist.org","nombreInstituto":"Salam University","tituloAdquirido":"Recruiting Manager","fechaInicioEdu":"2014-05-05","fechaTerminoEdu":"1994-04-17","cedula":274,"puesto":"Human Resources","funciones":"data-warehouse","empresa":"Yotz","fechaInicioExp":"1996-10-05","fechaTerminoExp":"2016-08-13","cursos":"nisi at nibh in hac habitasse platea dictumst aliquam augue quam","seminarios":"Consumer Non-Durables","diplomados":"Public Utilities","publicaciones":"architect clicks-and-mortar users","otros":"Hill","idiomas":"Albanian","entrevistado":true,"note":"nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices","trabajoEquipo":8,"liderazgo":5,"conocimientoTecnico":7,"facilidadComunicacion":4,"creatividad":8},
  {
    "nombres":"Lockwood","apellidos":"Meineken","sexo":"Male","fechaNacimiento":"1980-03-19","direccion":"7 Shelley Crossing","telefono":"498 591 7935","email":"lmeineken19@hatena.ne.jp","nombreInstituto":"Panzhihua University","tituloAdquirido":"Chief Design Engineer","fechaInicioEdu":"2014-07-14","fechaTerminoEdu":"2016-06-02","cedula":948,"puesto":"Marketing","funciones":"Total","empresa":"Blogtags","fechaInicioExp":"1994-12-31","fechaTerminoExp":"1994-02-18","cursos":"vestibulum sit amet cursus id turpis","seminarios":"Energy","diplomados":"Finance","publicaciones":"integrate proactive e-services","otros":"Parkway","idiomas":"Tamil","entrevistado":true,"note":"vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis","trabajoEquipo":5,"liderazgo":5,"conocimientoTecnico":3,"facilidadComunicacion":8,"creatividad":2},
  {
    "nombres":"Kimmy","apellidos":"Zuanelli","sexo":"Female","fechaNacimiento":"1991-04-02","direccion":"41 Meadow Valley Terrace","telefono":"262 362 6861","email":"kzuanelli1a@oakley.com","nombreInstituto":"Regent College","tituloAdquirido":"Computer Systems Analyst I","fechaInicioEdu":"2002-10-14","fechaTerminoEdu":"1996-07-21","cedula":425,"puesto":"Training","funciones":"composite","empresa":"Feedbug","fechaInicioExp":"2007-02-28","fechaTerminoExp":"1996-02-02","cursos":"erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla","seminarios":"Consumer Services","diplomados":"Technology","publicaciones":"monetize visionary infomediaries","otros":"Lane","idiomas":"Tok Pisin","entrevistado":false,"note":"ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien","trabajoEquipo":5,"liderazgo":2,"conocimientoTecnico":2,"facilidadComunicacion":8,"creatividad":1},
  {
    "nombres":"Phebe","apellidos":"Franzonello","sexo":"Female","fechaNacimiento":"1985-06-21","direccion":"1 Charing Cross Court","telefono":"403 915 5846","email":"pfranzonello1b@skype.com","nombreInstituto":"Grinnell College","tituloAdquirido":"Product Engineer","fechaInicioEdu":"2011-10-31","fechaTerminoEdu":"1998-04-12","cedula":459,"puesto":"Marketing","funciones":"Vision-oriented","empresa":"Twinte","fechaInicioExp":"2000-05-19","fechaTerminoExp":"2003-03-11","cursos":"turpis elementum ligula vehicula consequat morbi","seminarios":"Basic Industries","diplomados":"Consumer Services","publicaciones":"reintermediate proactive relationships","otros":"Terrace","idiomas":"Punjabi","entrevistado":true,"note":"sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget","trabajoEquipo":1,"liderazgo":3,"conocimientoTecnico":5,"facilidadComunicacion":4,"creatividad":8},
  {
    "nombres":"Banky","apellidos":"Kagan","sexo":"Male","fechaNacimiento":"1985-08-11","direccion":"0 Hauk Center","telefono":"678 596 2850","email":"bkagan1c@ted.com","nombreInstituto":"Universitas Swadaya Gunung Djati","tituloAdquirido":"Design Engineer","fechaInicioEdu":"2005-05-04","fechaTerminoEdu":"2002-03-17","cedula":604,"puesto":"Services","funciones":"empowering","empresa":"Lazz","fechaInicioExp":"2008-07-02","fechaTerminoExp":"2016-08-20","cursos":"congue risus semper porta volutpat quam pede lobortis","seminarios":"Consumer Durables","diplomados":"Consumer Services","publicaciones":"brand transparent partnerships","otros":"Lane","idiomas":"Aymara","entrevistado":false,"note":"odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id","trabajoEquipo":6,"liderazgo":7,"conocimientoTecnico":6,"facilidadComunicacion":3,"creatividad":9},
  {
    "nombres":"Genny","apellidos":"Damp","sexo":"Female","fechaNacimiento":"1998-08-19","direccion":"1 Hoard Lane","telefono":"890 340 9427","email":"gdamp1d@de.vu","nombreInstituto":"Ateneo de Manila University","tituloAdquirido":"Accounting Assistant IV","fechaInicioEdu":"2007-01-07","fechaTerminoEdu":"2017-07-03","cedula":437,"puesto":"Research and Development","funciones":"bi-directional","empresa":"Agivu","fechaInicioExp":"2007-12-09","fechaTerminoExp":"1999-04-22","cursos":"pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante","seminarios":"Consumer Services","diplomados":"n/a","publicaciones":"unleash viral synergies","otros":"Street","idiomas":"Somali","entrevistado":false,"note":"nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt","trabajoEquipo":7,"liderazgo":4,"conocimientoTecnico":2,"facilidadComunicacion":8,"creatividad":2}


];

exports.seed = function(knex, Promise) {
  return knex('curriculums')
    .del()
    .then(() => {
      return knex('curriculums')
        .insert(CVdataRows);
    });
}
